name: Update AppImage Manifest

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions: write-all

jobs:
  run:
    name: Parse AppImage Manifest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup install stable

      - name: Build
        run: |
          git clone https://github.com/AppImage/appimage.github.io.git
          cargo run --release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Update AppImage repo"
          push: true
          committer_name: Actions Bot
          committer_email: actions@github.com
